version: '3.1'

services:

  db_test:
    image: postgres
    container_name: xo_db
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
      POSTGRES_DB: xo_db
